# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('is_authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('date_added', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('is_auth', models.BooleanField(default=False)),
                ('is_commentable', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
