# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_users_into_person(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Person = apps.get_model('news', 'Person')
    users = User.objects.all()

    for user in users:
        person = Person(user=user)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_users_into_person),
    ]
