# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_person_fk_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_authorized',
            new_name='is_publicated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_authorized',
            new_name='is_publicated',
        ),
    ]
