# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 16:23
from __future__ import unicode_literals

from django.db import migrations


def noops(apps, schema_editor):
    pass


def copy_users_into_person(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Person = apps.get_model('news', 'Person')
    users = User.objects.all()

    for user in users:
        try:
            user.Person
        except Exception:
            person = Person(user=user)
            person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_is_authorized_to_is_publicated'),
    ]

    operations = [
        migrations.RunPython(copy_users_into_person, noops)
    ]
