# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_copy_user_into_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=b'')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_image', to='news.Person')),
            ],
        ),
    ]
