# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_personimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='image',
            field=models.ImageField(upload_to='person_thumbnail'),
        ),
    ]
