# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 12:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import news.apps.common.helpers
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0008_auto_20160606_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='tytu\u0142')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dodano')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('is_public', models.BooleanField(default=True, verbose_name='czy publiczna?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=news.apps.common.helpers.get_files_upload_path, verbose_name='obraz')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='liczba wy\u015bwietle\u0144')),
                ('title', models.CharField(max_length=250, verbose_name='tytu\u0142')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dodano')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('is_public', models.BooleanField(default=True, verbose_name='czy publiczny?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'get_latest_by': 'date_added',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='photos',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='galleries', to='news.Photo', verbose_name='zdj\u0119cia'),
        ),
    ]
