# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_image_photo_gallery_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Gallery'),
        ),
    ]
