# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_post_gallery_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added'], 'verbose_name': 'Galeria zdj\u0119\u0107', 'verbose_name_plural': 'Galerie zdj\u0119\u0107'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added'], 'verbose_name': 'Zdj\u0119cie', 'verbose_name_plural': 'Zdj\u0119cia'},
        ),
        migrations.AddField(
            model_name='photo',
            name='homepage',
            field=models.BooleanField(default=False, verbose_name='Czy na stronie domowej?'),
        ),
    ]
